apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  envs:
  - .env
  name: koalaops-sandbox-configmap
images:
- name: europe-central2-docker.pkg.dev/sandbox-397113/sandbox/koalaops-sandbox
kind: Kustomization
labels:
- pairs:
    app.kubernetes.io/version: ""
namePrefix: koalaops-sandbox-
namespace: koalaops-sandbox
resources:
- ../../base
